theme: jekyll-theme-minimal
google_analytics: UA-120752245-1
title: yuasabe
logo: https://avatars3.githubusercontent.com/u/5180742?s=400&u=2d2abb484ef4fca12fe432ac562b6ff69aa70278&v=4
github: [metadata]
markdown: kramdown